### ISSUE TITLE
JavaScript 30 

### ISSUE THREAD

**Issue by jim63** [jim63/jim63.github.io#15]
## WEEK3 Update CSS Variables with JS

純 CSS 可以設定變數並且用 JavaScript 操控，全瀏覽器支援。使用方法如下

```CSS
// 在 :root 裡面設置環境變數
:root {
  --base: #badaaa;
  --blur: 0px;
  --spacing: 10px;
}

// 取用時，使用 var(--variableName)
img {
  padding: var(--spacing);
  background: var(--base);
  filter: blur(var(--blur));
}
```

`document.querySelectorAll` 選到的是 NodeList，不是 Array。從 chrome 的 Dev tool 可以觀察到，如果把 array 印出來，選擇 `__proto__`，會看到一大堆 `method` 可以使用。但是如果是 NodeList 的話就沒有這麼多 `method` 可以使用。

`element.dataset` 會回傳一個 object ，裡面有所有 `data-*` 屬性的 key, pair

```
<input id="spacing" type="range" name="spacing" min="10" max="200" value="10" data-sizing="px" data-name="oledu">

console.log(document.querySelector('input').dataset);    
// will return an object DOMStringMap {sizing: "px", name: "oledu"}
```

可以透過 `document.documentElement.style.setProperty` 來設定 `:root{}` 裡面的變數 `document.documentElement.style.setProperty(--variableNmae,value);`

```
document.documentElement.style.setProperty(`--${this.name}`, this.value + suffix);

```
